const resList = [
  {
    id: 1,
    resName: "Taj Biryani",
    cusine: "Biryani, Chicken, Roti",
    rating: 4,
    price: "₹220",
    img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
  },
  {
    id: 2,
    resName: "Spicy Andhra Meals",
    cusine: "Andhra, Veg Meals, Fry",
    rating: 4.2,
    price: "₹180",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
  },
  {
    id: 3,
    resName: "Bombay Chaat ",
    cusine: "Chaat, Pani Puri, Bhel",
    rating: 4.5,
    price: "₹90",
    img: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
  },
  {
    id: 4,
    resName: "Coastal Catch",
    cusine: "Seafood, Fish Curry, Rice",
    rating: 4.1,
    price: "₹260",
    img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
  },
  {
    id: 5,
    resName: "Punjabi Rasoi",
    cusine: "North Indian, Paratha, Lassi",
    rating: 4.3,
    price: "₹200",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
  },
  {
    id: 6,
    resName: "Kerala Spice Villa",
    cusine: "Kerala, Appam, Stew, Fish",
    rating: 4.4,
    price: "₹230",
    img: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
  },
  {
    id: 7,
    resName: "Hyderabadi Zaika",
    cusine: "Biryani, Haleem, Kebabs",
    rating: 4.6,
    price: "₹250",
    img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
  },
  {
    id: 8,
    resName: "Chennai Tiffins",
    cusine: "South Indian, Idli, Dosa",
    rating: 4.0,
    price: "₹120",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
  },
  {
    id: 9,
    resName: "Guntur Mirchi Mess",
    cusine: "Andhra, Spicy Meals, Chicken",
    rating: 3.9,
    price: "₹190",
    img: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
  },
  {
    id: 10,
    resName: "Street Bites",
    cusine: "Snacks, Burgers, Fries",
    rating: 4.2,
    price: "₹110",
    img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
  },
  {
    id: 11,
    resName: "Delhi Tandoori",
    cusine: "Tandoori, Kebabs, Naan",
    rating: 4.5,
    price: "₹240",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
  },
  {
    id: 12,
    resName: "Rajasthani Dhaba",
    cusine: "Dal Baati, Gatte, Churma",
    rating: 4.1,
    price: "₹210",
    img: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
  },
  {
    id: 13,
    resName: "Cafe Italiano",
    cusine: "Pasta, Pizza, Espresso",
    rating: 4.3,
    price: "₹270",
    img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
  },
  {
    id: 14,
    resName: "Sushi Zen",
    cusine: "Sushi, Ramen, Miso Soup",
    rating: 4.7,
    price: "₹300",
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
  },
  {
    id: 15,
    resName: "Veggie Delight",
    cusine: "Pure Veg, Salads, Juices",
    rating: 4.0,
    price: "₹150",
    img: "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
  },
];

export default resList;